Repository FACG6/AMiDEAST, pull requests merged in 2019-04, with the labels that each got.

#49 server setup for express and react
  .gitignore
  Back/.eslintrc.json
  Back/.gitignore
  Back/app.js
  Back/index.js
  Back/package-lock.json
  Back/package.json
  Client/.gitignore
  Client/package-lock.json
  Client/package.json
  Client/public/favicon.ico
  Client/public/index.html
  Client/src/components/App.js
  Client/src/index.js
  Client/src/serviceWorker.js
  package-lock.json
  package.json
Labels: In-progress, Need-Review

#51 Back end file structure
  server/.eslintrc.json
  server/.gitignore
  server/app.js
  server/controllers/auth/login.js
  server/controllers/index.js
  server/controllers/staff/course.js
  server/controllers/staff/index.js
  server/controllers/staff/search.js
  server/controllers/staff/student.js
  server/controllers/student/apply.js
  server/controllers/student/home.js
  server/controllers/student/index.js
  server/controllers/student/profile.js
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/queries/addData.js
  server/database/queries/deleteData.js
  server/database/queries/editData.js
  server/database/queries/getData.js
  server/helpers/hashPassword.js
  server/helpers/validation-schema.js
  server/index.js
  server/middlewares/authentication.js
  server/middlewares/authorization.js
  server/package-lock.json
  server/package.json
  server/test/query-test.js
  server/test/router-test.js
Labels: for merge

#60 Layout
  Client/package-lock.json
  Client/package.json
  Client/src/components/App.js
  Client/src/components/Layout/Desktop/index.css
  Client/src/components/Layout/Desktop/index.js
  Client/src/components/Layout/DesktopFooter/index.css
  Client/src/components/Layout/DesktopFooter/index.js
  Client/src/components/Layout/HamburgerMenu/index.css
  Client/src/components/Layout/HamburgerMenu/index.js
  Client/src/components/Layout/Header/index.css
  Client/src/components/Layout/Header/index.js
  Client/src/components/Layout/Mobile/index.css
  Client/src/components/Layout/Mobile/index.js
  Client/src/components/Layout/MobileFooter/index.css
  Client/src/components/Layout/MobileFooter/index.js
  Client/src/components/Layout/SideBar/index.css
  Client/src/components/Layout/SideBar/index.js
  Client/src/components/common/Button/index.css
  Client/src/components/common/Button/index.js.js
  Client/src/components/common/Course/index.css
  Client/src/components/common/Course/index.js
  Client/src/components/common/DatePiker/index.css
  Client/src/components/common/DatePiker/index.js
  Client/src/components/common/Input/index.css
  Client/src/components/common/Input/index.js
  Client/src/components/common/Label/index.css
  Client/src/components/common/Label/index.js
  Client/src/components/common/Link/index.css
  Client/src/components/common/Link/index.js
  Client/src/components/common/LinkList/index.css
  Client/src/components/common/LinkList/index.js
  Client/src/components/common/PickDay/index.css
  Client/src/components/common/PickDay/index.js
  Client/src/components/common/PickTime/index.css
  Client/src/components/common/PickTime/index.js
  Client/src/components/common/Search/index.css
  Client/src/components/common/Search/index.js
  Client/src/components/common/Table/index.css
  Client/src/components/common/Table/index.js
  Client/src/components/contanier/Auth/index.css
  Client/src/components/contanier/Auth/index.js
  Client/src/components/contanier/staff/Courses/AddCourse/index.css
  Client/src/components/contanier/staff/Courses/AddCourse/index.js
  Client/src/components/contanier/staff/Courses/ViewCourse/index.css
  Client/src/components/contanier/staff/Courses/ViewCourse/index.js
  Client/src/components/contanier/staff/Courses/index.js
  Client/src/components/contanier/staff/Student/AddStudent/index.css
  Client/src/components/contanier/staff/Student/AddStudent/index.js
  Client/src/components/contanier/staff/Student/EditStudent/index.css
  Client/src/components/contanier/staff/Student/EditStudent/index.js
  Client/src/components/contanier/staff/Student/ViewStudent/index.css
  Client/src/components/contanier/staff/Student/ViewStudent/index.js
  Client/src/components/contanier/staff/Student/index.js
  Client/src/components/contanier/student/Apply/index.css
  Client/src/components/contanier/student/Apply/index.js
  Client/src/components/contanier/student/Coures/index.css
  Client/src/components/contanier/student/Coures/index.js
  Client/src/components/contanier/student/Profile/index.css
  Client/src/components/contanier/student/Profile/index.js
Labels: for merge

#69 input Component
  Client/src/components/common/Input/index.css
  Client/src/components/common/Input/index.js
Labels: Need-Review

#56 Database configuration
  package-lock.json
  package.json
  server/.gitignore
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/package-lock.json
  server/package.json
  server/test/query-test.js
Labels: Need-Review

#75 Layout
  Client/src/components/Layout/Mobile/index.js
  Client/src/components/contanier/student/StudentCourses/index.css
  Client/src/components/contanier/student/StudentCourses/index.js
Labels: Need-Review, urgent

#72 64 labeled component
  Client/src/components/common/Input/index.css
  Client/src/components/common/Input/index.js
  Client/src/components/common/Label/index.css
  Client/src/components/common/Label/index.js
  Client/src/components/common/LabeledInput/index.js
Labels: Need-Review

#71 Table component
  Client/src/components/common/Table/cell.js
  Client/src/components/common/Table/index.css
  Client/src/components/common/Table/index.js
Labels: Need-Review

#82 Readme File
  README.md
Labels: for merge

#73 19 sidebar component
  Client/package-lock.json
  Client/public/index.html
  Client/src/components/common/Link/index.css
  Client/src/components/common/Link/index.js
  Client/src/components/common/LinkList/index.css
  Client/src/components/common/LinkList/index.js
  Client/src/components/common/Sidebar/index.css
  Client/src/components/common/Sidebar/index.js
  Client/src/components/common/Sidebar/staticdata.js
Labels: Need-Review

#77 28 profile component
  Client/public/index.html
  Client/src/components/common/TextCard/index.css
  Client/src/components/common/TextCard/index.js
  Client/src/components/contanier/student/Profile/index.css
  Client/src/components/contanier/student/Profile/index.js
  Client/src/index.css
Labels: Approved, for merge

#78 Course List component
  Client/src/components/common/Button/index.css
  Client/src/components/common/Button/index.js
  Client/src/components/common/Button/index.js.js
  Client/src/components/common/Course/index.css
  Client/src/components/common/Course/index.js
  Client/src/components/contanier/student/Coures/index.css
  Client/src/components/contanier/student/Coures/index.js
  Client/src/components/contanier/student/Coures/staticData.js
Labels: Need-Review

#85 Style
  Client/src/components/common/Input/index.css
  Client/src/components/common/Input/index.js
  Client/src/components/common/LabeledInput/index.css
  Client/src/components/common/LabeledInput/index.js
Labels: Need-Review

#79 ِApply course component
  Client/src/components/common/PickDay/index.css
  Client/src/components/common/PickDay/index.js
  Client/src/components/contanier/student/Apply/index.css
  Client/src/components/contanier/student/Apply/index.js
Labels: Approved, Done, for merge

#80 Login Component
  Client/src/components/Layout/Mobile/index.js
  Client/src/components/assets/Image/amideasblue.png
  Client/src/components/common/Input/index.css
  Client/src/components/contanier/Auth/index.css
  Client/src/components/contanier/Auth/index.js
  Client/src/components/contanier/Auth/staticdata.js
Labels: Need-Review

#81 AppliedCourse
  Client/src/components/common/Course/index.css
  Client/src/components/common/Course/index.js
  Client/src/components/contanier/student/StudentCourses/index.css
  Client/src/components/contanier/student/StudentCourses/index.js
  Client/src/components/contanier/student/StudentCourses/staticData.js
Labels: Done, for merge

#90 My Courses Link
  Client/src/components/Layout/SideBar/index.js
  Client/src/components/Layout/SideBar/staticData.js
  Client/src/components/assets/Image/mycourses.png
Labels: Need-Review

#97 Install eslint
  .eslintrc.json
  package-lock.json
  package.json
  server/.eslintrc.json
  server/package-lock.json
  server/package.json
Labels: Need-Review, urgent

#96 Travis
  .travis.yml
Labels: Need-Review

#95 Testing
  package.json
  server/package.json
  server/test/Endpoints/index.js
  server/test/Endpoints/router-test.js
  server/test/Queries/index.js
  server/test/Queries/query-test.js
  server/test/index.js
  server/test/query-test.js
  server/test/router-test.js
Labels: Done, for merge

#100 Profile Backend
  .gitignore
  .travis.yml
  Client/package-lock.json
  package-lock.json
  package.json
  server/database/config/db_build.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/queries/getStudent.js
  server/package-lock.json
  server/package.json
  server/test/Queries/query-test.js
Labels: Need-Review

#88 Link Style
  Client/src/components/common/Link/index.css
  Client/src/components/common/Link/index.js
Labels: Done, for merge

#86 add student component
  Client/package.json
  Client/src/components/common/Input/index.js
  Client/src/components/common/Label/index.js
  Client/src/components/common/LabeledInput/index.css
  Client/src/components/contanier/staff/Student/AddStudent/index.css
  Client/src/components/contanier/staff/Student/AddStudent/index.js
  Client/src/helpers/validation-schema.js
Labels: Need-Review

#102 Profile Backend
  server/app.js
  server/controllers/index.js
  server/controllers/student/courses/getAll.js
  server/controllers/student/courses/getMy.js
  server/controllers/student/courses/index.js
  server/controllers/student/courses/postApply.js
  server/controllers/student/index.js
  server/controllers/student/user/get.js
  server/controllers/student/user/index.js
  server/package-lock.json
  server/package.json
  server/test/Endpoints/router-test.js
  server/test/Queries/query-test.js
Labels: Done, for merge

#104 103 all courses
  server/controllers/student/courses/getAll.js
  server/controllers/student/courses/index.js
  server/controllers/student/index.js
  server/database/queries/getAllCourses.js
  server/test/Endpoints/router-test.js
  server/test/Queries/query-test.js
Labels: Done, for merge

#106 Applied courses for student
  server/controllers/student/courses/getMy.js
  server/controllers/student/courses/index.js
  server/database/queries/getMyCourses.js
  server/test/Endpoints/router-test.js
  server/test/Queries/query-test.js
Labels: Done, for merge

#108 Post apply course
  server/controllers/student/courses/index.js
  server/controllers/student/courses/postApply.js
  server/database/queries/postApplyCourse.js
  server/test/Endpoints/router-test.js
Labels: Done, for merge

#109 Table component
  Client/src/components/common/Table/index.js
Labels: Need-Review

#87 Edit student
  Client/src/components/contanier/staff/Student/AddStudent/index.css
  Client/src/components/contanier/staff/Student/AddStudent/index.js
  Client/src/components/contanier/staff/Student/EditStudent/index.css
  Client/src/components/contanier/staff/Student/EditStudent/index.js
  Client/src/components/contanier/staff/Student/EditStudent/staticdata.js
  Client/src/helpers/validation-schema.js
Labels: Need-Review

#110 Edit the api
  server/controllers/courses/addCourse.js
  server/controllers/courses/course.js
  server/controllers/courses/courses.js
  server/controllers/courses/deleteCourse.js
  server/controllers/courses/index.js
  server/controllers/courses/level/getCoursesLevel.js
  server/controllers/courses/level/index.js
  server/controllers/courses/postApplyCourse.js
  server/controllers/courses/sudent/getCoursesStudent.js
  server/controllers/courses/sudent/index.js
  server/controllers/index.js
  server/controllers/student/addStudent.js
  server/controllers/student/course/getStudentsCourse.js
  server/controllers/student/course/index.js
  server/controllers/student/courses/getAll.js
  server/controllers/student/courses/getMy.js
  server/controllers/student/courses/index.js
  server/controllers/student/courses/postApply.js
  server/controllers/student/deleteStudent.js
  server/controllers/student/getStudent.js
  server/controllers/student/getStudents.js
  server/controllers/student/index.js
  server/controllers/student/level/getStudentsLevel.js
  server/controllers/student/level/index.js
  server/controllers/student/updateStudent.js
  server/controllers/student/user/index.js
  server/database/config/db_build.sql
  server/database/config/db_connection.js
  server/database/queries/addCourse.js
  server/database/queries/addData.js
  server/database/queries/addStudent.js
  server/database/queries/deleteCourse.js
  server/database/queries/deleteData.js
  server/database/queries/deleteStudent.js
  server/database/queries/editData.js
  server/database/queries/getAllCourses.js
  server/database/queries/getCourse.js
  server/database/queries/getCourses.js
  server/database/queries/getCoursesLevel.js
  server/database/queries/getCoursesStudent.js
  server/database/queries/getData.js
  server/database/queries/getStudents.js
  server/database/queries/getStudentsCourse.js
  server/database/queries/getStudentsLevel.js
  server/database/queries/postApplyCourse.js
  server/database/queries/updateStudent.js
  server/helpers/validation-schema.js
  server/package-lock.json
  server/package.json
  server/test/Endpoints/router-test.js
  server/test/Queries/query-test.js
Labels: Need-Review, in-review, urgent

#91 View course
  Client/src/components/App.js
  Client/src/components/Layout/Desktop/index.css
  Client/src/components/Layout/Desktop/index.js
  Client/src/components/common/Input/index.js
  Client/src/components/common/Label/index.js
  Client/src/components/contanier/staff/Courses/AddCourse/index.css
  Client/src/components/contanier/staff/Courses/AddCourse/index.js
  Client/src/components/contanier/staff/Courses/ViewCourse/index.css
  Client/src/components/contanier/staff/Courses/ViewCourse/index.js
  Client/src/components/contanier/staff/Courses/index.js
  Client/src/components/contanier/staff/Student/index.js
  server/controllers/student/courses/getAll.js
  server/controllers/student/courses/getMy.js
  server/controllers/student/courses/index.js
  server/controllers/student/courses/postApply.js
  server/controllers/student/user/get.js
  server/controllers/student/user/index.js
  server/database/config/db_connection.js
  server/database/queries/getAllCourses.js
  server/database/queries/getMyCourses.js
  server/package-lock.json
  server/package.json
  server/test/Queries/query-test.js
Labels: for merge

#98 view student component
  Client/src/components/contanier/staff/Student/ViewStudent/index.css
  Client/src/components/contanier/staff/Student/ViewStudent/index.js
Labels: for merge

#99 35 add course
  Client/src/components/common/Button/index.css
  Client/src/components/common/Input/index.css
  Client/src/components/contanier/staff/Courses/AddCourse/index.css
  Client/src/components/contanier/staff/Courses/AddCourse/index.js
  Client/src/components/contanier/staff/Student/index.js
  package-lock.json
  package.json
  server/database/queries/addData.js
Labels: Need-Review
